parser: babel-eslint
extends:
  - jason/react
  - plugin:jsx-a11y/recommended
settings:
  react:
    version: detect
env:
  node: true
  browser: true
plugins:
  - jsx-a11y

overrides:
  - files: www/**/*
    env:
      es6: true
  - files: stories/**/*
    rules:
      no-console: off
