parser: '@typescript-eslint/parser'
extends:
  - jason/react
  - plugin:jsx-a11y/recommended
  - prettier
settings:
  react:
    version: detect
env:
  node: true
  browser: true
plugins:
  - jsx-a11y
  - '@typescript-eslint'
rules:
  '@typescript-eslint/no-unused-vars':
    - error
    - ignoreRestSiblings: true

overrides:
  - files: www/**/*
    env:
      es6: true
  - files: stories/**/*
    rules:
      no-console: off
